#!/bin/sh
# Kurzaufruf des Messprogramms (Kammer fahren, stabil warten, Stufe messen), im Ordner schneehoehensensor:
#   ./programm 20 -40 -50 -60 -70 20 --stabil 30
exec python3 "$(dirname "$0")/skripte/messprogramm.py" "$@"
